name: figma_icon_builder
description: Fetch and export icons from figma
version: 0.3.0
repository: https://github.com/bjartebore/figma_icon_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^0.5.1
  figma_icon: ^1.0.0
  code_builder: ^4.0.0
  concurrent_queue: ^1.3.0
  console: ^4.1.0
  dart_style: ^2.0.1
  dotenv: ^3.0.0
  figma: ^3.0.0
  glob: ^2.0.1
  http: ^0.13.0
  path: ^1.8.0
  recase: ^4.0.0
  xml: ^5.1.2
  
dev_dependencies:
  import_sorter: ^4.4.2
  